language: node_js
node_js:
- '0.10'
before_install:
- npm install -g gulp
script:
- gulp build --require coffee-script/register
deploy:
  provider: heroku
  api_key:
    secure: YXT1c/60L1tMxuxwtFRoQVGHHevxb+lemo/wxODhNhzn6jfDBukQ+Cj3Uhf8LvCmtmjPt5Il9nuVnvY70b5seiJEEcgLk60mB70y+mAHahHP2Lva0zj7TXIAbaVdwNG1915MbhtGyKFSBItut+G49KomO9pjKR2j9wCrLhXp9fQ=
  app: invention
  on:
    repo: pgremo/invention
